version: '3'
services:
  db:
    image: postgres:12.3
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    env_file: .env
  web:
    build: .
    image: gurzu-shopify
    command: bash -c "bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file: .env
    environment:
      - ENABLE_BOOTSNAP=true
  resque:
    image: gurzu-shopify:latest
    command: bash -c "bundle exec rails environment resque:work QUEUE=*"
    volumes:
      - .:/app
      - /app/app/tmp
    depends_on:
      - redis
    links:
      - smtp
    env_file: .env
    environment:
      - ENABLE_BOOTSNAP=false
  webpacker:
    image: gurzu-shopify:latest
    environment:
      - NODE_ENV=development
      - RAILS_ENV=development
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
      - NODE_OPTIONS="--max_old_space_size=4096"
    command: bash -c "yarn && rm -rf /rails/public/packs && bin/webpack-dev-server"
    volumes:
      - .:/app
      - /app/app/tmp
    ports:
      - '3035:3035'
  redis:
    image: redis:6.0
    ports:
      - "6379:6379"
  smtp:
    image: mailhog/mailhog
    ports: 
      - 1025:1025
      - 8025:8025