default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= Rails.application.credentials[Rails.env.to_sym][:database][:max_threads] { 5 } %>
  database: <%= Rails.application.credentials[Rails.env.to_sym][:database][:name] %>
  username: <%= Rails.application.credentials[Rails.env.to_sym][:database][:user] %>
  password: <%= Rails.application.credentials[Rails.env.to_sym][:database][:password] %>
  host: <%= Rails.application.credentials[Rails.env.to_sym][:database][:host] %>

development:
  <<: *default

# Do not set this db to the same as development or production.
test:
  <<: *default
  database: <%= Rails.application.credentials.test[:database][:name] %>

nightly:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
